// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YaoDemoApi.Context;

#nullable disable

namespace YaoDemoApi.Migrations
{
    [DbContext(typeof(YaoDemoContext))]
    [Migration("20230617090218_yao")]
    partial class yao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");
#pragma warning restore 612, 618
        }
    }
}
